### ISSUE TITLE
Instructions or automation script to make installing and running this easier

### ISSUE THREAD

**Issue by theunsa** [Marcelloos/CSP_Test#1]
Hi @Marcelloos 

Op die oomblik verwag jy dat baie deur ons self gedoen moet word om jou kode te kan hardloop. Jou README gee nie eens behoorlik instruksie nie en jy noem slegs die dependencies in jou report. Ek het die python dependencies geinstall soos in jou pdf en mysql db geskep met user etc, maar hardloop in nog probleme in ... dit is glad nie die idee dat ander devs moet sukkel om aan die gang te kom nie.

- [x] Maak gebruik van 'n requirements.txt file of soortgelyke automation script om dit makliker te maak vir 'n developer om van scratch af dadelik die nodige dependencies in te trek en jou kode te kan uitvoer
- [x] Ook so vir die mysql db ... jy gee geen instruksies dat een nodig is of wat die opstelling daarvoor moet wees nie vir die user nie en aanvaar iemand moet jou kode lees om te sien dit is "statisticsdb" en "pi:pi". Jy kan noem dat mysql nodig is maar is veronderstel om die res van hierdie goed te automate. Docker kan jou maat wees hierso.
- [x] Commit jou report ook in hierdie repo

Ek hoop jy hierdie uitsorteer sodat ons mooi jou coding challenge kan evalueer.

**Comment by Marcelloos** [comment]
Amper klaar nog net Vraag 1 ook in docker automate , het in n paar probleeme vasgeloop wat baie tyd gevat het. Op die oomblik hoe jy net die docker compose up statement the run en hoopelik werk dit soos dit nou 100% werk hier. Het die README geopdateer en gaan later net nog add en bietjie probeer mooier laat lyk.
Baie dankie vir die comments dit het my baie gehelp om die service te verbeter.(daar is well nog baie plek vir verbetering)
Sal oor n ruk Question 2 se updated containerized code push.

Hoop jy het n lekker naweek gehad en n lekker dag verder

**Comment by theunsa** [comment]
Jy seker jy het hierdie getoets? Ek kry volgende error ... lyk of daar komma kort?

```
.....
app_1  | 0.5
app_1  | MySQL connection is closed
app_1  | Traceback (most recent call last):
app_1  |   File "single.py", line 5, in <module>
app_1  |     from Ram_usage import RAM
app_1  |   File "/project/Ram_usage.py", line 25
app_1  |     connection = mysql.connector.connect(host='db',  database='demodbs', user='root',password='root'auth_plugin='mysql_native_password')
app_1  |                                                                                                               ^
app_1  | SyntaxError: invalid syntax
question1_app_1 exited with code 1
```

**Comment by Marcelloos** [comment]
Ja ek het dit getoets sal gou weer kyk , dit het gewerk to ek dit opgelaai het. Sal gou kyk het n merge gedoen en het dalk een komma uitgelaat. Sal nou dadelik kyk en weer toets.

Sent from Mail for Windows 10

**Comment by Marcelloos** [comment]
Fixed, en het sommer die Bytes received code slightly verander dat hy die network adapter auto select since n mens vroer manually in die code moes set na watter een jy will track. Nou track hy die een met die hoogste byte count. Daar was ook n random s aan die bokant van my tempreture file wat ek ook reggemaak het. Dankie vir die trugvoering
